### ISSUE TITLE
setup-emsdk can't find recent SDK's

### ISSUE THREAD

**Issue by vadimkantorov** [mymindstorm/setup-emsdk#19]
Hi!

I've tried specifying recent Emscripten versions such as `2.0.21` or `2.0.24`, both lead to emsdk printing `No tool or SDK found by name '2.0.24'`:
``` 
    steps:
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v9
        with:
          version: 2.0.24
```

Any idea what am I missing?
