### ISSUE TITLE
Cache system libraries

### ISSUE THREAD

**Issue by Algunenano** [mymindstorm/setup-emsdk#6]
First of all, thanks a lot for putting this out there; I've started using it today and it worked flawlessly in the first try.

This is not an issue but a feature request. It seems like the cache is being stored at the end of ` Run mymindstorm/setup-emsdk@v5`, so system libraries built during the "normal" compilation are not cached.

In my test build, generating these libraries take ~1m 40s (out of ~2m). Extract:
```
Tue, 07 Jul 2020 12:11:04 GMT
cache:INFO: generating system library: libc.a... (this will be cached in "/home/runner/work/bq-tiler/bq-tiler/emsdk-cache/emsdk-master/upstream/emscripten/cache/wasm-lto/libc.a" for subsequent builds)
Tue, 07 Jul 2020 12:12:08 GMT
cache:INFO:  - ok
Tue, 07 Jul 2020 12:12:08 GMT
cache:INFO: generating system library: libcompiler_rt.a... (this will be cached in "/home/runner/work/bq-tiler/bq-tiler/emsdk-cache/emsdk-master/upstream/emscripten/cache/wasm-lto/libcompiler_rt.a" for subsequent builds)
```

Is there any way to setup a post run step to the build (either manually in each job or by adding an option to the action) to get those system libraries to also be cached? As far as I know, these generated system libraries only depend on the emcc version, so caching everything together should be safe.

**Comment by Algunenano** [comment]
In the end I was able to do this by using cache@v2 directly with something like this:

```
env:
  EM_VERSION: 1.39.18
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{ runner.os }}${{env.EM_VERSION}}
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: mymindstorm/setup-emsdk@v5
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: Build library
        run: make -j2
      - name: Run unit tests
        run: make check
```

With this the build step went from ~2m 10s to ~30 seconds.
