### ISSUE TITLE
Emscripten sanity check deletes cache during build

### ISSUE THREAD

**Issue by musicEnfanthen** [mymindstorm/setup-emsdk#9]
Hi and thanks for this action.

We are encoutering a weird issue, that is both hard to track and to reproduce:

Our use-case: We use setup-emsdk action to install and cache emscripten in a "pre-cache" job, and then restore and activate it from cache in a following job to avoid multiple downloads and installations with matrix builds. Our setup looks like follows:

```
env:
  EMSCRIPTEN_VERSION: latest
  EMSCRIPTEN_CACHE_FOLDER: emsdk-cache

<snip>
jobs:
setup_emscripten:
    name: Set up and cache emscripten
    runs-on: ubuntu-20.04
    steps:
      - name: Set up cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.EMSCRIPTEN_CACHE_FOLDER }}-${{ github.run_id }}
          key: ${{ runner.os }}-emsdk-${{ env.EMSCRIPTEN_VERSION }}-${{ github.run_id }}

      - name: Set up emsdk
        uses: mymindstorm/setup-emsdk@v7
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: ${{ env.EMSCRIPTEN_CACHE_FOLDER }}-${{ github.run_id }}
          no-cache: true

<snip>

build_js:
    runs-on: ubuntu-20.04
    needs: [setup_emscripten]
    strategy:
      matrix:
        toolkit:
          <4 build options>
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Restore cache
        id: restore_cache
        uses: actions/cache@v2
        with:
          path: ${{ env.EMSCRIPTEN_CACHE_FOLDER }}-${{ github.run_id }}
          key: ${{ runner.os }}-emsdk-${{ env.EMSCRIPTEN_VERSION }}-${{ github.run_id }}

      - name: Set up emsdk (cache not found)
        uses: mymindstorm/setup-emsdk@v7
        if: steps.restore_cache.outputs.cache-hit != 'true'
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          no-cache: true
      - name: Set up emsdk (cache found)
        if: steps.restore_cache.outputs.cache-hit == 'true'
        uses: mymindstorm/setup-emsdk@v7
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: ${{ env.EMSCRIPTEN_CACHE_FOLDER }}-${{ github.run_id }}
          no-cache: true
```

The issue: With some build runs, it seems that the emscripten config changes during the run and clears the cache (triggered by its sanity check). This seems to happen unpredicatbly, i.e. sometimes it works without problems, sometimes the issue appears.

You can find a failing run in https://github.com/musicEnfanthen/verovio/actions/runs/322146695 .
The sanity check info is thrown in: https://github.com/musicEnfanthen/verovio/runs/1292826609?check_suite_focus=true#step:8:55

Is this a known issue? Is there something wrong in our setup?

Thanks in advance.

**Comment by mymindstorm** [comment]
Hi, thanks for the detailed report! This is not a known issue with the action. I think this is being caused by using `latest` and caching together. Preferably, you should be declaring versions for builds with the cache and using builds without caching for `latest`. This can be problematic in some situations e.g. if a cache is detected, the "latest" version will not be downloaded.

Other things I noticed:
- This may be caused by appending `run_id` to the cache folder, the folder name changing may be causing emscripten to become confused between caches.
- you don't need to have the if statement, the action will handle no cache folder existing just fine
- actions-cache-folder implies no-cache

This example config from the README should help:

```yaml
env:
  EM_VERSION: 1.39.18
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v7
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: Build library
        run: make -j2
      - name: Run unit tests
        run: make check
```
